name = "demo"
version = "1.0.0"
description = "Demo project showcasing unitest features"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
envoy = ">= 1.1.0 and < 2.0.0"
unitest = { path = "../.." }
