name = "unitest"
version = "1.4.3"
description = "Test runner with random ordering, tagging, and CLI filtering"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jtdowney", repo = "unitest" }

[dependencies]
argv = ">= 1.0.2 and < 2.0.0"
clip = ">= 1.2.0 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
glance = ">= 6.0.0 and < 7.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
prng = ">= 5.0.0 and < 6.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
spinner = ">= 1.3.1 and < 2.0.0"
tobble = ">= 2.0.2 and < 3.0.0"

[dev-dependencies]
birdie = ">= 1.5.3 and < 2.0.0"
qcheck = ">= 1.0.3 and < 2.0.0"
